name: jira-test

on:
  pull_request:
    types: [opened]

jobs:
  jira-test:
    name: Test for jira-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_KEY }}

      - name: Create
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: FTB
          issuetype: Task
          summary: |
            Build completed for ${{ github.repository }}
          description: |
            Compare branch

      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"
